name: ivan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  mysql1: ^0.20.0
  sqflite: ^2.0.0+4
  path: ^1.8.3
  file_picker: ^5.0.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.20


  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg
    - assets/images/fondo.jpg
    - assets/images/fondo1.jpg
    - assets/images/fondo2.jpg
    - assets/images/fondo3.jpg    
  fonts:
    - family: indie_flower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: permanent_marker  
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
  

